//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryAgent
    {
        public int Id { get; set; }
        public string NameAgent { get; set; }
        public string NewNameAgent { get; set; }
        public Nullable<int> OldPriority { get; set; }
        public Nullable<int> NewPriority { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
