//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AgentDetails
    {
        public string Тип_агента { get; set; }
        public string Наименование_агента { get; set; }
        public string Номер_телефона { get; set; }
        public int Приоритет { get; set; }
        public Nullable<decimal> Скидка_агента { get; set; }
        public string Количество_продаж { get; set; }
        public string Описание { get; set; }
        public int Id { get; set; }
        public string ImageLogo { get; set; }
    }
}
